/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : SYSTEM

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 10/07/2023 17:17:13
*/


-- ----------------------------
-- Table structure for WTGL_YWCJ
-- ----------------------------
CREATE TABLE "WTGL_YWCJ" (
  "CJSJ" TIMESTAMP(6),
  "WTMC" VARCHAR2(255 BYTE),
  "SCDDH" VARCHAR2(255 BYTE),
  "CPXH" VARCHAR2(255 BYTE),
  "WTLY" VARCHAR2(255 BYTE),
  "XWJJSJ" TIMESTAMP(6),
  "WTXL" VARCHAR2(255 BYTE),
  "ZYCD" VARCHAR2(255 BYTE),
  "YZRBM" VARCHAR2(255 BYTE),
  "WTLB" VARCHAR2(255 BYTE),
  "WTMS" VARCHAR2(255 BYTE),
  "WTZT" VARCHAR2(255 BYTE),
  "ID" VARCHAR2(255 BYTE) NOT NULL,
  "GBSJ" TIMESTAMP(6),
  "WCTS" VARCHAR2(255 BYTE),
  "TJSJ" TIMESTAMP(6),
  "JSSJ" TIMESTAMP(6),
  "GZXT" VARCHAR2(255 BYTE),
  "JJSJ" TIMESTAMP(6),
  "WTDB" NUMBER,
  "WDWT" NUMBER,
  "CJBMID" VARCHAR2(255 BYTE),
  "CJKSID" VARCHAR2(255 BYTE),
  "CJRID" VARCHAR2(255 BYTE),
  "GXH" VARCHAR2(255 BYTE),
  "WTSJ" VARCHAR2(255 BYTE),
  "XCPHWT" VARCHAR2(255 BYTE),
  "LDPS" VARCHAR2(255 BYTE),
  "SCFJ" VARCHAR2(255 BYTE),
  "CQTS" VARCHAR2(255 BYTE),
  "WTBH" VARCHAR2(255 BYTE),
  "CJR" VARCHAR2(255 BYTE),
  "CJKS" VARCHAR2(255 BYTE),
  "CJBM" VARCHAR2(255 BYTE),
  "YXCD" VARCHAR2(255 BYTE),
  "YJSJ" TIMESTAMP(6),
  "DQZRR" VARCHAR2(255 BYTE),
  "ZRJH" VARCHAR2(255 BYTE),
  "SJRJS" VARCHAR2(255 BYTE),
  "LXFK" VARCHAR2(255 BYTE),
  "PC" VARCHAR2(255 BYTE),
  "SB" VARCHAR2(255 BYTE),
  "QWFKSJ" VARCHAR2(255 BYTE),
  "BHSJ" VARCHAR2(255 BYTE),
  "JHSJ" VARCHAR2(255 BYTE),
  "YZR" CLOB
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WTGL_YWCJ"."CJSJ" IS '问题创建时间';
COMMENT ON COLUMN "WTGL_YWCJ"."WTMC" IS '问题名称';
COMMENT ON COLUMN "WTGL_YWCJ"."SCDDH" IS '生产订单号';
COMMENT ON COLUMN "WTGL_YWCJ"."CPXH" IS '产品型号';
COMMENT ON COLUMN "WTGL_YWCJ"."WTLY" IS '问题来源';
COMMENT ON COLUMN "WTGL_YWCJ"."XWJJSJ" IS '希望解决时间';
COMMENT ON COLUMN "WTGL_YWCJ"."WTXL" IS '问题细类';
COMMENT ON COLUMN "WTGL_YWCJ"."ZYCD" IS '重要程度';
COMMENT ON COLUMN "WTGL_YWCJ"."YZRBM" IS '预知人部门';
COMMENT ON COLUMN "WTGL_YWCJ"."WTLB" IS '问题类别';
COMMENT ON COLUMN "WTGL_YWCJ"."WTMS" IS '问题描述';
COMMENT ON COLUMN "WTGL_YWCJ"."WTZT" IS '问题状态';
COMMENT ON COLUMN "WTGL_YWCJ"."ID" IS '问题ID';
COMMENT ON COLUMN "WTGL_YWCJ"."GBSJ" IS '关闭时间';
COMMENT ON COLUMN "WTGL_YWCJ"."WCTS" IS '完成天数';
COMMENT ON COLUMN "WTGL_YWCJ"."TJSJ" IS '提交时间';
COMMENT ON COLUMN "WTGL_YWCJ"."JSSJ" IS '接收时间';
COMMENT ON COLUMN "WTGL_YWCJ"."GZXT" IS '是否跟踪协同';
COMMENT ON COLUMN "WTGL_YWCJ"."JJSJ" IS '解决时间';
COMMENT ON COLUMN "WTGL_YWCJ"."WTDB" IS '我的问题待办数量';
COMMENT ON COLUMN "WTGL_YWCJ"."WDWT" IS '我的待办待办数量';
COMMENT ON COLUMN "WTGL_YWCJ"."CJBMID" IS '创建部门ID';
COMMENT ON COLUMN "WTGL_YWCJ"."CJKSID" IS '创建科室ID';
COMMENT ON COLUMN "WTGL_YWCJ"."CJRID" IS '创建人ID';
COMMENT ON COLUMN "WTGL_YWCJ"."GXH" IS '工序号';
COMMENT ON COLUMN "WTGL_YWCJ"."WTSJ" IS '升级人ID';
COMMENT ON COLUMN "WTGL_YWCJ"."XCPHWT" IS '是否现场配合问题';
COMMENT ON COLUMN "WTGL_YWCJ"."LDPS" IS '是否领导批示';
COMMENT ON COLUMN "WTGL_YWCJ"."SCFJ" IS '是否上传附件';
COMMENT ON COLUMN "WTGL_YWCJ"."CQTS" IS '超期天数';
COMMENT ON COLUMN "WTGL_YWCJ"."WTBH" IS '问题编号';
COMMENT ON COLUMN "WTGL_YWCJ"."CJR" IS '创建人';
COMMENT ON COLUMN "WTGL_YWCJ"."CJKS" IS '创建科室';
COMMENT ON COLUMN "WTGL_YWCJ"."CJBM" IS '创建部门';
COMMENT ON COLUMN "WTGL_YWCJ"."YXCD" IS '影响程度';
COMMENT ON COLUMN "WTGL_YWCJ"."YJSJ" IS '预警时间';
COMMENT ON COLUMN "WTGL_YWCJ"."DQZRR" IS '当前责任人';
COMMENT ON COLUMN "WTGL_YWCJ".ZRJH IS '升级责任人级数';
COMMENT ON COLUMN "WTGL_YWCJ"."SJRJS" IS '升级责任人的级数';
COMMENT ON COLUMN "WTGL_YWCJ"."LXFK" IS '是否例行反馈';
COMMENT ON COLUMN "WTGL_YWCJ"."PC" IS '批次';
COMMENT ON COLUMN "WTGL_YWCJ"."SB" IS '设备';
COMMENT ON COLUMN "WTGL_YWCJ"."QWFKSJ" IS '期望解决时间';
COMMENT ON COLUMN "WTGL_YWCJ"."BHSJ" IS '闭环时间';
COMMENT ON COLUMN "WTGL_YWCJ"."JHSJ" IS '激活时间';
COMMENT ON COLUMN "WTGL_YWCJ"."YZR" IS '阅知人';

-- ----------------------------
-- Records of WTGL_YWCJ
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table WTGL_YWCJ
-- ----------------------------
ALTER TABLE "WTGL_YWCJ" ADD CONSTRAINT "WTGL_YWCJ_PK" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table WTGL_YWCJ
-- ----------------------------
ALTER TABLE "WTGL_YWCJ" ADD CONSTRAINT "SYS_C007473" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WTGL_YWCJ" ADD CONSTRAINT "SYS_C007780" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
