/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : SYSTEM

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 10/07/2023 17:15:40
*/


-- ----------------------------
-- Table structure for WTGL_CJLS
-- ----------------------------
CREATE TABLE "WTGL_CJLS" (
  "ZS" VARCHAR2(255),
  "CJWTID" VARCHAR2(255),
  "WTJS" VARCHAR2(255),
  "SBXH" VARCHAR2(255),
  "JH" VARCHAR2(255),
  "CPXH" VARCHAR2(255),
  "GXH" VARCHAR2(255),
  "GXMC" VARCHAR2(255),
  "BCRQ" VARCHAR2(255),
  "TBR" VARCHAR2(255),
  "BJZRKS" VARCHAR2(255),
  "BJZRR" VARCHAR2(255),
  "WTMS" VARCHAR2(255),
  "TBJSSJ" VARCHAR2(255),
  "TBDQST" VARCHAR2(255),
  "JSR" VARCHAR2(255),
  "JJFA" VARCHAR2(255),
  "LSID" VARCHAR2(255) NOT NULL,
  "WTZT" VARCHAR2(255),
  "SCDDH" VARCHAR2(255),
  "PC" VARCHAR2(255),
  "SFMY" VARCHAR2(255),
  "CJSJ" DATE DEFAULT CURRENT_TIMESTAMP,
  "TBRID" VARCHAR2(255),
  "BJRID" VARCHAR2(255),
  "JSRID" VARCHAR2(255),
  "CJBMKS" VARCHAR2(255),
  "WTMC" VARCHAR2(255)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "WTGL_CJLS"."ZS" IS '展示';
COMMENT ON COLUMN "WTGL_CJLS"."CJWTID" IS '车间问题ID';
COMMENT ON COLUMN "WTGL_CJLS"."WTJS" IS '接收按钮';
COMMENT ON COLUMN "WTGL_CJLS"."SBXH" IS '设备型号';
COMMENT ON COLUMN "WTGL_CJLS"."JH" IS '件号';
COMMENT ON COLUMN "WTGL_CJLS"."CPXH" IS '产品型号';
COMMENT ON COLUMN "WTGL_CJLS"."GXH" IS '工序号';
COMMENT ON COLUMN "WTGL_CJLS"."GXMC" IS '工序名称';
COMMENT ON COLUMN "WTGL_CJLS"."BCRQ" IS '班产日期';
COMMENT ON COLUMN "WTGL_CJLS"."TBR" IS '提报人';
COMMENT ON COLUMN "WTGL_CJLS"."BJZRKS" IS '被叫科室';
COMMENT ON COLUMN "WTGL_CJLS"."BJZRR" IS '被叫人';
COMMENT ON COLUMN "WTGL_CJLS"."WTMS" IS '问题描述';
COMMENT ON COLUMN "WTGL_CJLS"."TBJSSJ" IS '提报-接收时间';
COMMENT ON COLUMN "WTGL_CJLS"."TBDQST" IS '提报-当前时间';
COMMENT ON COLUMN "WTGL_CJLS"."JSR" IS '接收人';
COMMENT ON COLUMN "WTGL_CJLS"."JJFA" IS '解决方案';
COMMENT ON COLUMN "WTGL_CJLS"."LSID" IS 'ID';
COMMENT ON COLUMN "WTGL_CJLS"."WTZT" IS '问题状态';
COMMENT ON COLUMN "WTGL_CJLS"."SCDDH" IS '生产订单号';
COMMENT ON COLUMN "WTGL_CJLS"."PC" IS '批次';
COMMENT ON COLUMN "WTGL_CJLS"."SFMY" IS '是否满意';
COMMENT ON COLUMN "WTGL_CJLS"."CJSJ" IS '创建时间';
COMMENT ON COLUMN "WTGL_CJLS"."TBRID" IS '提报人ID';
COMMENT ON COLUMN "WTGL_CJLS"."BJRID" IS '被叫人ID';
COMMENT ON COLUMN "WTGL_CJLS"."JSRID" IS '接收人ID';
COMMENT ON COLUMN "WTGL_CJLS"."CJBMKS" IS '创建部门科室';
COMMENT ON COLUMN "WTGL_CJLS"."WTMC" IS '问题名称';

-- ----------------------------
-- Records of WTGL_CJLS
-- ----------------------------
INSERT INTO "WTGL_CJLS" VALUES ('BBB', '1', '1', '1', '1', '1', '1', '1', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL, NULL, TO_DATE('2023-07-01 15:04:32', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL);
INSERT INTO "WTGL_CJLS" VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, NULL, NULL, NULL, TO_DATE('2023-07-01 15:29:54', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL, NULL);

-- ----------------------------
-- Primary Key structure for table WTGL_CJLS
-- ----------------------------
ALTER TABLE "WTGL_CJLS" ADD CONSTRAINT "WT_CJLS_PK" PRIMARY KEY ("LSID");

-- ----------------------------
-- Checks structure for table WTGL_CJLS
-- ----------------------------
ALTER TABLE "WTGL_CJLS" ADD CONSTRAINT "SYS_C007459" CHECK ("LSID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "WTGL_CJLS" ADD CONSTRAINT "SYS_C007792" CHECK ("LSID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
